### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by Laurie1996** [cmda-bt/pt-course-19-20#104]
# Job Story + stagic site

## Name
Laurie Bosman

## Class
tech3

## GitHub username
https://laurie1996.github.io/staticsite

## Job story
Wanneer ik door mensen/dieren/objecten heen swipe/scroll wil ik door persoonlijke foto's heen kunnen swipen, zodat ik het profiel kan bekijken.

**Comment by michaeldzjap** [comment]
Een paar visuele dingen die mij opvielen:

- De foto en beschrijving worden nu niet gecentreerd op de pagina. Ook voor mobile kan dit er een beetje vreemd uitzien (landscape mode). Het centreren van deze elementen kan je in principe op precies dezelfde manier doen als je hebt gedaan voor je header.
- Als je de pagina kleiner maakt scalen de buttons alleen horizontaal en niet verticaal, zodat ze ovaal van vorm worden, dat ziet er een beetje gek uit
- De foto scaled niet mee als je de pagina kleiner maakt. Met name als de app voor mobile bedoeld is dan geeft dat misschien niet het resultaat dat je voor ogen hebt.

Daarnaast moet je gaan bedenken hoe je het dynamisch foto's laden gaat oplossen wanneer je als gebruiker gaat "swipen". Elke keer een nieuwe pagina laden met de nieuwe foto is een optie, maar je zou ook kunnen kijken naar het laden van foto content door middel van AJAX (toegegeven; dat is waarschijnlijk wel een stuk complexer qua implementatie, maar geeft wel een mooiere user experience). En wil je echt ook een swipe functionaliteit aanbieden of wil je het simpel houden en het "swipen" alleen doen d.m.v. de 2 buttons (of beide)?
