### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by RowinRuizendaal** [cmda-bt/pt-course-19-20#178]
# Job Story + static site

## Name
Rowin Danilo Ruizendaal

## Class
203 | TECH 4

## GitHub username
https://github.com/RowinRuizendaal/project-tech => 
https://rowinruizendaal.github.io/project-tech/static-website/index.html

## Job story

When I want to get a nice date, I want to be able to register on a dating platform so I can get to know new people that I could possibly go on a date with. I also want to be able to login to my account on any device & moment.

**Comment by TuriGuilano** [comment]
Rowin, great job!
Good defined job story, and your prototype looks really slick, well done.

Small tip; reduce the size of your images used in your static prototype; they are currently each above 1mb - which is a lot. Try reducing size in photoshop or sketch - also compress with tinypng. 

It's also nice to look into responsive images with html's srcset - this renders a specific image based on the view width e.g.

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

Good job Rowin, keep it up.
