### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by Vuurvos1** [cmda-bt/pt-course-19-20#183]
# Job Story + static site

## Name
Sam de Kanter

## Class
Tech 4

## GitHub username
Vuurvos1
**Repo** \
https://github.com/Vuurvos1/projectTech
**Static Site** \
https://vuurvos1.github.io/projectTech/staticSite/

## Job story
Once I have met someone I like, I want to be able to send them a message from any device to start a conversation. I also want these messages to be secure so no one else can read them.

**Comment by TuriGuilano** [comment]
Hi Sam, interesting approach - seems like a fun challenge. With respect to your job story, please keep the format of When... I want to... so I can... see link for more details: https://jtbd.info/replacing-the-user-story-with-the-job-story-af7cdee10c27

With respect to your prototype - nicely done! Please keep in mind that your feature must also be working without javascript - so think about elements that you can use to send data to a server when no javascript is enabled..
