### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by mikehov** [cmda-bt/pt-course-19-20#185]
# Job Story + stagic site

## Name
Mike Hovenier

## Class
TECH-4

## GitHub username
https://mikehov.github.io/Dating-app/
https://mikehov.github.io/Dating-app/match.html

**Repo:**
https://github.com/mikehov/Dating-app

## Job story
_When I'm chilling in my room listening to my music playlist, I want be notified that I have a match with someone or someone likes me, so I can see who it is and maybe get to know them._

(Swiping and Notifications)

**Comment by TuriGuilano** [comment]
Hi Mike, good start - I would like to suggest a small change in your job story;

I want to be notified that I have a match - or when someone likes me. 

Good job on the static html / css, however; your feature needs to be working without Javascript as well. So think about suitable html elements for the setup, for example; a form element works without javascript..
