### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by shabier** [cmda-bt/pt-course-19-20#187]
# Job Story + stagic site

## Name

sjagoori
## Class

tech-4
## GitHub username

[repo](https://github.com/sjagoori/project-tech/tree/master/static_page)
[site](https://sjagoori.github.io/project-tech/static_page/feature.html)
[mirror](https://project-tech.now.sh/)
## Job story

When I am using a dating app to meet with other users, I want to register on that app with information that describes and defines me along with my preferences, so I can find users that have something in common with me and possibly match with them.

**Comment by TuriGuilano** [comment]
Please revision your job story - your current job story pretty much defines a dating app as whole. Try to lay an emphasis on a specific part, in your case the registration - you could do something like;

_When I feel the need to make use of a dating app, I want to be able to create an account where I can provide information that describes and defines me along with my preferences, so I can be able to create a personalised profile._ 

This way you lay an emphasis on a specific spart and allows you to create the following feature:
- login / registration
- adjust profile settings

Remember; eventually you will work together with other people in a team - say one of these team members has liking functionalities; that suits your job story perfect.
