### ISSUE TITLE
Octocat

### ISSUE THREAD

**Issue by kiara1404** [cmda-bt/pt-course-19-20#190]
# Octocat

## Name
Kiara

## Class
tech 4

## GitHub username
https://github.com/kiara1404

## Links
https://github.com/kiara1404/github-slideshow
https://github.com/kiara1404/hello-world
https://github.com/kiara1404/patchwork

## Feedback
goed te volgen, goed te doen.

**Comment by TuriGuilano** [comment]
Keep it up 💪🏼
