### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by sreen020** [cmda-bt/pt-course-19-20#192]
# Job Story + stagic site

## Name
Sjoerd Reen

## Class
TECH 4

## GitHub username
website = https://sreen020.github.io/Project-TECH/
repo = https://github.com/sreen020/Project-TECH

## Job story
Ik als eenzaam, gepensioneerd persoon wil kunnen filteren op de afstand tussen mij en andere personen omdat ik niet goed ter been ben om meer dan een X aantal km te reizen.

**Comment by TuriGuilano** [comment]
Hi Sjoerd, please formulate your job story in English. 

I find your job story original and nicely thought of! Your static feature looks well in progress. Please keep in mind that the feature also must work when no javascript is enabled.. so think of means to send data to a server without javascript.. (look at form element). Good luck!
