### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by SjorsWijsman** [cmda-bt/pt-course-19-20#200]
# Job Story + static site

## Name

Sjors Wijsman

## Class

Tech 4

## GitHub username

https://github.com/SjorsWijsman/project-tech

## Job story

When I am looking for new matches on a dating app, I want to see their favourite auditory or visual art, so I can find people with similar creative interests.

**Comment by TuriGuilano** [comment]
Hi Sjors, could you extend your job story a bit more with respect to context / situation / expected outcome.

For example - what is your expected outcome when you have found these matches with similar creative interests?
