### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by Froezt** [cmda-bt/pt-course-19-20#201]
# Job Story + static site

## Name
Floris Roest

## Class
206

## GitHub username
pages: https://froezt.github.io/datingapp-feature/.
profile: https://github.com/Froezt

## Job story
When I am looking for new people to match with on MyStyle, I want to be able to see what type of clothing these people wear and if we have the same interests. If I like someone, I want to know if they liked me as well.

**Comment by TuriGuilano** [comment]
Interesting job story story, please do elaborate.

I am missing the So I can.. part - (this is the expected outcome). You can find addittional information here; https://jtbd.info/replacing-the-user-story-with-the-job-story-af7cdee10c27

Also, I would suggest focussing on one aspect - the clothing part I assume is a lot of work: e.g. you can click on a user and see what t-shirts they are wearing - pants - socks - hats and so on..
