### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by Bjornborgie** [cmda-bt/pt-course-19-20#202]
# Job Story + stagic site

## Name
Bjorn Kouw
## Class
Tech 4
## GitHub username
Bjornborgie
## Job story
Wanneer ik thuis s’avonds met mijn laptop op de bank een profiel van een persoon zie die ik leuk vind, wil ik een aanleiding hebben om met haar te kunnen praten wanneer zij mij ook leuk vind, over filosofische vraag. zodat daarna een gesprek volgt waarin we elkaar beter kunnen leren kennen wat kun uitmonden tot een date en een relatie.

**Comment by TuriGuilano** [comment]
Hi Bjorn, first up please write your job story in English! 

Job story overall is nice, however I don't understand the philosophical question part - could you elaborate?

**Comment by TuriGuilano** [comment]
Nice to see that you have a base setup for your prototype. Next lecture we will talk about how to make your feature's functionality consistent throughout the process of progressive enhancement - meaning; your feature should at all times work, even if only html is available and no javascript is supported by the browser. When keeping this approach in mind - you want to restructure your html and use the form element. Form's still work without javascript, it actually was the means of sending data to a server before javascript was available in the browser. 

You can read more about this in chapter 18 of eloquent javascript, which is also study material for upcoming lecture.

Your headed in the good direction Bjorn, keep it up.
