### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by rosavoogd** [cmda-bt/pt-course-19-20#203]
# Job Story + static site

Ik heb mijn bestanden geupload bij de code. Het mapje heet static-website. 
Ik hoop dat dit zo oke is ingeleverd.

## Name
Rosa Voogd

## Class
Tech-4

## GitHub username
https://github.com/rosavoogd/datingapp

## Job story
When I am looking for a pet on the app, 
I want to be able to filter the pets based on their needs,
So I can provide the pet with everything they need to live a happy life

**Comment by TuriGuilano** [comment]
Hi Rosa, good job. Could you make the "when part" (situation)and the So I can (expected outcome) part, a bit more explicit? As in; 

When im feeling alone and am looking for a new pet to keep me company, 
....I want to.... (this part is fine) 
So I can determine if I am capable to provide the pet with...

Your HTML looks like it contains a good base for future work, nicely done with the form etc.
