### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by NathanNeelis** [cmda-bt/pt-course-19-20#204]
# Job Story + stagic site

## Name
Nathan Neelis

## Class
Tech-4

## GitHub username
[NathanNeelis](https://github.com/NathanNeelis/Project-Tech)

## Job story
**When** I'm bored at home, at the beginning of the evening, watching cooking shows on Netflix, while I'm already done with all my homework  
**I want to** get in touch with people that have the same interests as me  
**So I** can ask them if they want to do something fun that is in both our interests.

[Link to the Job story Wiki](https://github.com/NathanNeelis/Project-Tech/wiki/Job-stories)

## Static website
All of the files for the static website are actually in the folder "static".  
Have in mind that I only created the **home page** and the **Search page**.  
[Here is the link](https://nathanneelis.github.io/Project-Tech/static/index.html) for the GitHub pages.

**Comment by TuriGuilano** [comment]
Nathan this is great work!! From defining your job story to extensively creating a first iteration of a static feature, nicely done.

Feedback; look at future functionalities of the dating app and revision your html - ask yourself the question; what would be the best way to store / send this data when I am on a device which is unable to run javascript? (tip: look at form element - this works even without javascript which allows you to still have a 'working product' even though no javascript is available -  this is also a requirement of the course).
