### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by Falicer** [cmda-bt/pt-course-19-20#205]
# Job Story + stagic site

## Name
Raekwon Gerold

## Class
Tech-4

## GitHub username
[Raekwon](https://github.com/Falicer/Blok_Tech)
[Static webpage dating app](https://falicer.github.io/Blok_Tech/)

## Job story
**When** a conversation is reaching a dead end and you can't find a topic to talk about, I **want to** have an option to request a conversation topic to use in that conversation, **So** I/We can keep the conversation going if we both want to on a new and refreshed topic.

**Comment by TuriGuilano** [comment]
Nice and original idea! I am interested in what type of feature this will result.

Good job as well on the prototype - looks good. Please keep in mind that your feature also needs to work when no JS is enabled, so think about html elements that are suitable for this use case, e.g. a form element.
