### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by AsaMarjew** [cmda-bt/pt-course-19-20#206]
# Job Story + stagic site

## Name
Asa Marjew

## Class
tech 4

## GitHub username
https://github.com/AsaMarjew/Dating-app
Github pages
https://asamarjew.github.io/Dating-app/

## Job story
"When I've been matched online with someone I want to start a private conversation to get to know them, so I can make a decision if this is the right person for me. "

**Comment by TuriGuilano** [comment]
Hi Asa, clear job story. Could you try and extend a bit more on the matched online part - for instance; you have been matched based on what? Specific interests for example. 

Nice that you also made a start with your prototype! However take a close look at the upcoming functionalities that are required for this job story and think of the required elements; for example - if you want to be able to start a private conversation with someone you need send/store data, maybe a form element in more suited to store all your "potential" matches in?
