### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by SimonPlanje** [cmda-bt/pt-course-19-20#208]
# Job Story + stagic site

## Name
Simon Planje
## Class
Tech 4
## GitHub username

static-site: https://simonplanje.github.io/DatingApp/
repository: https://github.com/SimonPlanje/DatingApp
## Job story

When I am bored during the Corona period, all my friend are not available and just want to lay down for a few minutes.
I still want to socialize to have a good laugh with like minded people.
So I do not get bored while I have more spare time, and instead have some fun with strangers.

**Comment by TuriGuilano** [comment]
Hi Simon, your job story could be defined a bit more specific;

e.g.: When I am bored during the Corona period and am in the need of social contact with like minded people, I want to be able to quickly find these like minded people so I can start a conversation with them and talk about our shared interests.

By defining your job story as mentioned above you create the situation - state your motivation and define the expected outcome. Please take the example above and redefine your job story.
