### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by kiara1404** [cmda-bt/pt-course-19-20#210]
# Job Story + stagic site

## Name
Kiara

## Class
Tech 4

## GitHub username
https://kiara1404.github.io/cmd_tech_dating-app/index.html

## Job story
When I'm looking for a workout partner on this app, I want to get notified when somebody compatible is found so I can send them a message.

**Comment by TuriGuilano** [comment]
First up, nicely done with the static website. With respect to your job story I have some suggestions; can you try to expand it a bit more?

_When I am looking for a workout partner to train with, I want to be able to be notified when someone compatible to my type of training is found so I can send them a message_

By defining your job story as mentioned above it allows you to create a feature where users can fill in their goals / preferred type of training etc.
