### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by ParvinBDJ** [cmda-bt/pt-course-19-20#211]
# Job Story + static site

## Name
Parvin Bungenberg de Jong
## Class
203
## GitHub username
https://github.com/ParvinBDJ/Dating-App/tree/master/project-tech
## Job story
When you are watching a movie at home and are interested in people that watch the same kind of movies as you do, I want to match people that have the same movie interests, So I can make them happy and have them watch movies and maybe do more things together.

**Comment by TuriGuilano** [comment]
Write the job story with yourself in the center of it:

When **I am watching** a movie at home and **am interested** in people that watch the same kind of movies **as me**, **I want to** be able to match... 

Also, what will the feature be?
