### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by uxtothemax** [cmda-bt/pt-course-19-20#230]
# Job Story + stagic site

## Name
Romy

## Class
tech-4

## GitHub username
uxtothemax

## Job story
When I wake up in the early morning to start a fresh, new day where anything is possible, I want to set my preferences for the perfect adventuring partner, so we can go slay and/or romance a dragon together.

## GitHub Repo
https://github.com/uxtothemax/shrekconnect/tree/gh-pages

**Comment by TuriGuilano** [comment]
@Job story, nice! Pretty unique. Im curious what your dating feature will look like. With respect to code - I see you have integrated a form element, which is nice. Could you elaborate on how you intend to develop your feature? 

As for github pages - you have now created a branch of your project being a github-pages branch. You can create a separate repository named github-pages as I show in the tutorial - https://github.com/TuriGuilano/githubpages this way you can statically host your project.

Good luck!
