### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by RowinRuizendaal** [cmda-bt/pt-course-19-20#232]
# Config

## Name
Rowin Ruizendaal

## Class
203 | Tech 04

## GitHub username
https://github.com/RowinRuizendaal

## GitHub repository
https://github.com/RowinRuizendaal/project-tech

## Add a screenshot of your editor
![Editor](https://rowinruizendaal.github.io/project-tech/img/progressive-enhancement/editor.PNG)

## Summary

Installed:
Beatify,
ESLint,
Remote - WSL,
VsIcons

**Comment by TuriGuilano** [comment]
Nice Rowin
