### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by saskiapool** [cmda-bt/pt-course-19-20#233]
# Config

## Name
Saskia

## Class
Tech-4

## GitHub username
https://github.com/saskiapool

## GitHub repository
https://github.com/saskiapool/meal-match/wiki/Week-4-PT

## Add a screenshot of your editor
<img width="1129" alt="Schermafbeelding 2020-05-19 om 21 27 03" src="https://user-images.githubusercontent.com/63783883/82369594-900e4100-9a17-11ea-8c2b-39318e1e5e43.png">

## Summary
Did research on some extensions and linters. Installed ESLint but haven't quite found out how it works yet. In the screenshot above you can see which extensions I have installed in my code editor. Also made a small requirements list and used the MoSCoW method on that list.

**Comment by TuriGuilano** [comment]
If you want additional info regarding the config or the parts that you find difficult let me know.
