### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by SjorsWijsman** [cmda-bt/pt-course-19-20#234]
# Config

## Name

Sjors Wijsman

## Class

Tech 4

## GitHub username

SjorsWijsman

## GitHub repository

https://github.com/SjorsWijsman

## Add a screenshot of your editor

![Editor Screenshot](https://i.ibb.co/hYQjKdZ/Screenshot-2020-05-21-at-17-08-04.png)

## Summary

Installed eslint with strongloop config, cleaned up eslint errors and used a beautify package (Atom Beautify) to make my code look as beautiful as my mom. Added a pretest script that runs the linter to check for any linter issues that my editor didn't catch I guess.

**Comment by TuriGuilano** [comment]
Nice job Sjors
