### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by mikehov** [cmda-bt/pt-course-19-20#236]
# Config

## Name
Mike Hovenier

## Class
Tech-4

## GitHub username
https://github.com/mikehov

## GitHub repository
https://github.com/mikehov/Dating-app

## Add a screenshot of your editor
![My color theme](https://github.com/mikehov/Dating-app/wiki/images/colortheme-monokai.png "My color theme at this moment").

## Summary
I installed the ESLint, implemented in my project, try to change some rules but haven't really got that to work. I tried a lot of extensions to making coding easier to organize and type. Changed up my color theme a bit. Added MoSCoW to my Jobstories. I definitely see the use of using ESLint but found it very hard to implement with the rules. Really liked the different extensions, love try extensions out and see what I like to personalize my code editor. I slowly start to understand the project, but still typing my own code seems to be a obstacle. I'm hoping by working on the project all the pieces will come together.

**Comment by TuriGuilano** [comment]
Good summary - image is broken though.. 😭

**Comment by mikehov** [comment]
> Good summary - image is broken though.. 😭

Adjusted ;D
