### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by victorboucher** [cmda-bt/pt-course-19-20#238]
# Config

## Name
Victor Boucher

## Class
tech-4

## GitHub username
https://github.com/BVictorB

## GitHub repository
https://github.com/BVictorB/cmd-dating-app

## Add a screenshot of your editor
![Screenshot 2020-05-22 at 20 44 15](https://user-images.githubusercontent.com/10921830/82699466-0192fd00-9c6d-11ea-938f-69bb2a526f61.png)

## Summary
* Updated wiki (not totally up to date, but I am working on it)
* Installed ESLint NPM package and VSCode extension
* Setup ESLint config
* Handlebars setup
* Sass setup
* Express setup

**Comment by TuriGuilano** [comment]
👏🏼 Victor
