### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by shabier** [cmda-bt/pt-course-19-20#239]
# Config

## Name

sjagoori
## Class

tech-4
## GitHub username

[sjagoori](https://github.com/sjagoori)
## GitHub repository

[project-tech](https://github.com/sjagoori/project-tech)
[wiki](https://github.com/sjagoori/project-tech/wiki)

## Add a screenshot of your editor

![](https://raw.githubusercontent.com/sjagoori/project-tech/master/images/snapshot.png)
## Summary

I've installed ESlint using Google's style gude as base. It fits and matches the writing style I've gotten used to over the months and looks cleaner than Airbnb's where they, for example, use the $ sign. As for extentions (along ESlint) i've installed [Markdown All In One](https://github.com/yzhang-gh/vscode-markdown) to speed up text editing in markdown and [Beautifier](github.com/HookyQR/VSCodeBeautify) to handle SCSS/CSS formatting.

**Comment by TuriGuilano** [comment]
Good job!
