### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by Falicer** [cmda-bt/pt-course-19-20#240]
# Config

## Name
Raekwon Gerold

## Class
Tech 4

## GitHub username
[Falicer](https://github.com/Falicer)

## GitHub repository
[Blok Tech Repo](https://github.com/Falicer/Blok_Tech)

## Add a screenshot of your editor
Does it look fancy? No tbh
![](https://i.imgur.com/DU8Wgtw.png)
Image of my extensions downloaded
![](https://i.imgur.com/5NbcWjC.png)

## Summary

While doing research on which extensions and linters to add to my editor, I only downloaded linter-ESlint the others I was already using so far.
All the extensions I have you can see in the picture above. (atm still using Atom, I might switch back to VSCode or Brackets, I've used them all 3 before and still don't know which one is the most comfortable for me)

**Comment by TuriGuilano** [comment]
Nice job.
