### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by bommezijn** [cmda-bt/pt-course-19-20#241]
# Config

## Name
Nathan Bommezijn

## Class
TECH-4

## GitHub username
[Dewarian](www.github.com/dewarian)

## GitHub repository
[bt-dating-app](https://github.com/dewarian/bt-dating-app)
[wiki](https://github.com/dewarian/bt-dating-app/wiki)

## Add a screenshot of your editor
![image](https://user-images.githubusercontent.com/13199349/82724843-2cb33600-9cd9-11ea-921a-9ac6fa04122a.png)

## Summary
Learned about linting, best use cases, rules, and how to configure ESLint. I also got that Google linting is pretty strict, but I do see the benefit of it.

Also, before this assignment, I fluffed up my editor with a new font (went from FiraCode to Operator Mono 😏). I also found out I am a hoarder of extensions.

**Comment by TuriGuilano** [comment]
Nice job!🏅
