### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by NathanNeelis** [cmda-bt/pt-course-19-20#244]
# Config

## Name
Nathan Neelis

## Class
Tech 4

## GitHub username
[Nathan Neelis](https://github.com/NathanNeelis)

## GitHub repository
https://github.com/NathanNeelis/Project-Tech

## Add a screenshot of your editor
![code editor](https://raw.githubusercontent.com/NathanNeelis/Project-Tech/master/Styleguide/editor/editor_nathan.jpg)

#### Linter
For the linters I installed ESLint and Prettier. Still figuring out which rules to apply and how to implement prettier.

[link to linters research](https://github.com/NathanNeelis/Project-Tech/wiki/Linters)

#### For extensions I installed:
• Material theme 
• Bracket pair colorizer
• Indent-rainbow
• Auto Rename Tag

Resource for the extensions:
codeSTACKr. (2019). Top 10 Best VS Code Extensions (2020) [Videobestand]. YouTube. Geraadpleegd van https://www.youtube.com/watch?v=c5GAS_PMXDs

**Comment by TuriGuilano** [comment]
🔥
