### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by Vuurvos1** [cmda-bt/pt-course-19-20#246]
# Config

## Name
Sam de Kanter

## Class
Tech 4

## GitHub username
https://github.com/vuurvos1

## GitHub repository
https://github.com/Vuurvos1/projectTech

## Add a screenshot of your editor

![Screenshot of my code editor](https://github.com/Vuurvos1/projectTech/wiki/images/CodeEditorLooks.png "Screenshot of my code editor")

## Summary
I installed and played with multiple extensions like
* File utils
* GitLens
* Bookmarks
* vscode-icons
* ESLint
* Prettier

I also looked a different themes for my code editor

**Comment by TuriGuilano** [comment]
💪🏼
