### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by Femke-ooster** [cmda-bt/pt-course-19-20#65]
# Job Story + stagic site

## Name
Femke Oosterbaan

## Class
Tech 3

## GitHub username
Femke_Ooster
https://github.com/Femke-ooster/dating-app/tree/master/statische-website
Website:
https://femke-ooster.github.io/dating-app/statische-website/

## Job story
Wanneer er een foto van de gebruiker wordt geliked, wil hij dat hij deze kan zien als een push bericht, zodat hij weet wanneer of wie zijn foto heeft geliked.

**Comment by michaeldzjap** [comment]
Een kleine tip; elke keer wanneer je op een van de drie icons klikt een nieuwe pagina. Dit is een beetje onhandig. Dit kost niet alleen tijd (de tijd om een nieuwe pagina te laden), maar is ook niet ideaal vanuit UX oogpunt. Stel, je hebt een aantal invulvelden op je pagina die een gebruiker heeft ingevuld, nu klik je op een icon, waardoor een nieuwe pagina geladen wordt en de gebruiker is dan al zijn ingevulde content kwijt.

Een mooiere manier zou zijn om hier wat JavaScript toe te passen (al dan wel of niet in combinatie met wat simpele CSS), zodat je de notification zichtbaar / onzichtbaar kan maken zonder dat je van pagina hoeft te veranderen (hint: CSS rule `display:none;` in combinatie met een JavaScript 'click' event listener).
