### ISSUE TITLE
Carlijn Bruin: first feedbackmoment

### ISSUE THREAD

**Issue by carlijnbruin** [cmda-bt/pt-course-19-20#67]
# Job Story + static site

## Name
Carlijn Bruin

## Class
Tech 3

## GitHub username
https://github.com/carlijnbruin/bloktech/tree/master/week_1/myapp
https://github.com/carlijnbruin/bloktech/wiki/Aantekeningen-Project-Tech Gemaakte huiswerk

## Job story
Wanneer ik opzoek ga naar een date, wil ik mij kunnen registreren op een datingssite en een profiel aanmaken, zodat ik in in contact kan komen met andere singles en zij met mij.

**Comment by michaeldzjap** [comment]
Ziet er tot dusver prima uit. Paar kleine dingen:

- Momenteel is het mogelijk door alle schermen te navigeren zonder content in te vullen. M.a.w. ik zou nu in principe een profiel kunnen aanmaken zonder iets in te vullen. Daar is een reden voor (die inderdaad moeilijk nu anders op te lossen is, omdat je een puur statische site hebt). Weet je waarom dit nu zo is en wat je (later) kan doen om dit te voorkomen?
- Is het de bedoeling dat de app alleen voor mobile bestemd is? Ik zeg dit omdat als je je scherm breder maakt de layout naar onderen wordt gepushed (oorzaak: CSS `margin` rule gespecificeerd in procenten). Dit is misschien niet ideaal, in ieder geval iets om je bewust van te zijn.

**Comment by carlijnbruin** [comment]
Bedankt!

-  Klopt inderdaad. Dit heb ik momenteel aangepast, door middel van de button te veranderen naar een 'submit' button. Daarnaast heb ik ook wat requirements neergezet bij de input fields, zoals dat het wachtwoord min. 6 karakters moet hebben, een hoofdletter en een cijfer. Door middel van backend te gebruiken, kan je nu niet meer verder zonder iets in te vullen. Backend slaat de input die gebruikers invullen nu ook op in een array. Zo heb ik het aangepast. Ik weet niet of dit helemaal de juiste manier is en of ik het volledig snap, waarom je eerst zo door de pagina heen kon gaan zonder iets in te vullen en nu niet meer, maar het is wel opgelost nu.

- Dat klopt. Ik wilde het alleen voor mobile maken, daarom valt de CSS wat naar beneden als je het scherm groter maakt. Is het erg als je het enkel voor mobile maakt?

Bedankt voor de nuttige feedback!
