### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by RickGroot** [cmda-bt/pt-course-19-20#73]
# Job Story + stagic site

## Name
Rick Groot

## Class
Tech_3

## GitHub username
Rickert41    
https://rickert41.github.io/project_tech/week2/staticsite/index.html

## Job story
Wanneer ik aan het zoeken ben wil ik alleen kunnen matchen met mensen die dezelfde interesses als mij hebben, zodat ik alleen met de leukste personen match.

**Comment by michaeldzjap** [comment]
Een paar kleine opmerkingen:

- De grid layout werkt opzich prima. Misschien wil je wel wat marge houden als je de pagina zo klein maakt zodat er nog net 2 article elementen naast elkaar passen?
- De like button wil je waarschijnlijk altijd volledig zichtbaar houden? (hint: `z-index` CSS rule).
- Als je nu op de info knop klikt wordt er een nieuwe pagina geladen. Dit is een beetje overkill en laat de info zien van alle personen in plaats van alleen de geselecteerde persoon. Dit zou je mooier kunnen oplossen met wat JavaScript of zelfs puur alleen met CSS (kijk [hier](https://www.w3schools.com/howto/howto_js_accordion.asp) eens naar bv.).
