### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by hihijenny** [cmda-bt/pt-course-19-20#75]
# Job Story + stagic site

## Name
Jenny 

## Class
Tech 2

## GitHub username
https://github.com/hihijenny/blok-tech/tree/master/project-tech

## Job story
Wanneer ik op een dating app zit wil ik weten waar mijn potentiële date graag eet zodat we inspiratie hebben voor een eerste date.

**Comment by rouws** [comment]
Hi Jenny,

De link hierboven werkt niet, maar ik zie een andere repo met daar een static site in. Deze kan ik alleen nog niet goed zien. In je nieuwe repo zie dat je met express aan de gang bent, top! Ook heb je al redelijk uitgebreide css. Ik mis een wiki voor je ontwerpen en onderzoek. Ik kan nu niet goed zien wat je van plan bent en kan ook niet goed meedenken. Het enige wat ik echt goed zie is je job story en dat is te weinig.
