### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by Jeroen777** [cmda-bt/pt-course-19-20#77]
# Job Story + stagic site

## Name
Jeroen

## Class
Tech-2

## GitHub username
https://github.com/Jeroen777/BlockTech/tree/master/static%20website

## Job story
Wanneer ik in de bus zit wil ik kunnen matchen met andere artiesten zodat ik met hen kan samenwerken

**Comment by rouws** [comment]
Hi Jeroen,
Ik zie een ontwerp in je wiki, heel goed dat je al een schets hebt.  Het lijkt me mogelijk wat veel, maar je kunt er makkelijk 1 of 2 stappen tussenuit halen als het te veel blijkt te zijn. Je static site is nog niet af zo te zien, dus daar kan ik nu niet zo veel aan zien. Al met al kan ik nog niet heel goed feedback geven ben ik bang
