### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by MariaS20** [cmda-bt/pt-course-19-20#78]
# Job Story + stagic site

## Name
Tess Smit

## Class
Tech2

## GitHub username
https://github.com/MariaS20/Blok-Tech/tree/master/code

## Job story
Wanneer ik op een ander device zit, wil ik makkelijk kunnen inloggen, zodat ik hier niet veel tijd aan hoef te besteden.

**Comment by rouws** [comment]
Beste Tess,
Je gaat je richten op inloggen, maar dat is wel erg klein. Ik kan me voorstellen dat je het registreren / wachtwoord vergeten etc. er ook bij neemt. Misschien was je dat van plan al hoor, want ik zie het wel bij je ontwerpen. 

Je loopt best goed bij dat is mooi. Ik loop even alle onderdelen langs:
- Je benchmark is vrijwel leeg. Wat bij je style guide staat, kun je hierin zetten, maar kijk bij je benchmark ook naar functionaliteit en interactiepatronen. Met name als het gaat om inloggen en registreren, want daar heb je vast nog iets aan
- Je onderzoek naar progressive enhancement is nog erg beperkt. Kun je voorbeelden vinden. Heb je ideeen hoe je het principe zelf gaat toepassen?
- Klopt het dat je bij de style guide vooral hebt gekeken naar hoe bestaande apps zijn vormgegeven?  Bedenk ook wat de vormgeving van jouw web app wordt
- Je wireframes en wireflow zijn prima
- je static site is prima, er zijn nog meer views, maar die kun je misschien in je templates gaan zetten.
- je hebt een klein beginnetje gemaakt met express, heel goed. je mag gaan nadenken over de routes en views die je nodig hebt, kom je daar uit?

Kortom, je bent lekker bezig!
