### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by maxwieringa** [cmda-bt/pt-course-19-20#80]
# Job Story + stagic site

## Name
Max Wieringa

## Class
Tech-2 

## GitHub username
https://github.com/maxwieringa/blok-tech

## Job story
Wanneer ik op de bank zit wil ik weten wat iemand grappig vind zodat ik weet of we dezelfde humor hebben

**Comment by rouws** [comment]
Hi Max,
het is niet mogelijk voor mij om goede feedback te geven nog, omdat je nog te weinig hebt staan. ik zie nog bijna niets in je wiki staan. Ik zie wel een job story en dat je bezig bent met express al een beetje. Je static site is nog niet af.
