### ISSUE TITLE
first feedbackmoment - Jade Schreuder

### ISSUE THREAD

**Issue by JadeSsst** [cmda-bt/pt-course-19-20#81]
# Job Story + stagic site

## Name
Jade Schreuder

## Class
TECH 3

## GitHub username
JadeSsst

## Job story
Wanneer ik o peen datingsite zit om liefde te zoeken, wil ik voorkeuren kunnen opgeven en filteren zodat ik mijn perfecte match kan vinden.

**Comment by michaeldzjap** [comment]
Klinkt als een originele job story en je statische [site](https://jadessst.github.io/Blok-TECH/Tech/feature/index.html) ziet er ook duidelijk en verzorgd uit. Ik ben benieuwd hoe je hier verder technisch invulling aan gaat geven. Het daadwerkelijke filteren en zoeken gaat een leuke technische (maar zeker niet onmogelijke) uitdaging worden.
