### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by junecha** [cmda-bt/pt-course-19-20#82]
# Job Story + stagic site

## Name
Chun 

## Class
Tech 2

## GitHub username
https://github.com/ChunningTatum/Blok_tech
## Job story
When I am matched with another person on a dating app, I want to be able to talk to this person, so I can engage with the person that I am interested in.

When I make a profile, I want to be able to upload a picture, so I can express myself better.

When I make a profile, I want to have a way to let other people know what my interests are, so I can tell others what I like.

When I am on a dating app, I want to be able to 'choose' people that I like and 'remove' others I don't, so I can match with the people I do like.

**Comment by rouws** [comment]
Beste Chun,

in je wiki vind ik je benchmark al goed. Ik verwacht wel dat je elke week een pagina toevoegt met onderzoek en ontwerp. Je hebt een heleboel job stories, waarschijnlijk twijfel je welke je wilt doen? Waar twijfel je dan over? Ik kan moeilijk feedback geven als ik niet weet welke job story je gaat doen en hoe je ontwerp eruit ziet.

De code die ik zie is misschien deels van vorig jaar? was je toen vooral bezig met login en registreren dus?
