### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by jor-s** [cmda-bt/pt-course-19-20#83]
# Job Story + stagic site

## Name
Jordy Sahit

## Class
Tech-2

## GitHub username
https://github.com/sahitj001/be-20

## Job story
Als gebruiker wil ik wat over mijzelf kunnen vertellen zodat meer mensen over mij te weten kunnen komen.

**Comment by rouws** [comment]
Hi Jordy,

Klopt het dat de code die ik zie vooral van vorig jaar is? Daar was je al heel ver in gekomen. Wat is je plan voor dit jaar? Wil je doorgaan met het login / registeer / profiel ding? Bedoel je dat met de bovenstaande job story? 
Ik mis wel een wiki nog voor je onderzoek en schetsen.
