### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by khualu** [cmda-bt/pt-course-19-20#84]
# Job Story + stagic site

## Name
Andy

## Class
TECH 2

## GitHub username
[Khualu/Project Tech](https://github.com/khualu/project_tech/wiki/Week-2)

## Job story
When I'm online, I want to match potential partners with a top 3 of videogames I play, SO I can play a game date with them.

**Comment by rouws** [comment]
Hi Andy,
Je bent heel goed bezig, ik zie een goede benchmark en styleguide. Je hebt ook een ontwerp gemaakt. Je lijkt de stap van de static site over te slaan en je bent vol in express bezig met ejs tot nu toe. Dat ziet er goed uit. Top!
