### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by saralof** [cmda-bt/pt-course-19-20#85]
# Job Story + stagic site

## Name
Sara Lof

## Class
Tech 2

## GitHub username
https://github.com/saralof/projectTech

## Job story
Wanneer ik gematched word, wil ik zo snel mogelijk zoveel mogelijk over iemand te weet komen zodat ik weet of er een klik is.

**Comment by rouws** [comment]
Hi Sara,
je bent heel goed bezig tot nu toe. Je benchmark bevat interessante inzichten. Het zou goed zijn als je allerlei screenshots bijvoegt. Weet je hoe je afbeeldingen in je wiki kunt toevoegen? Je styleguide mag je in markdown gaan neerzetten. Het is ook belangrijk dat je in je repo zo langzamerhand de 'echte' code gaat zetten van je web app en dan geen mapjes per vak meer zetten. Dat hoeft niet.

Dus in je wiki zet je per week welk onderzoek je hebt gedaan en je ontwerpen. De echte code mag in je repo komen.
