### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by SBindels** [cmda-bt/pt-course-19-20#86]
# Job Story + stagic site

## Name
Sjoerd Bindels

## Class
tech-2

## GitHub username
SBindels

## Job story
Wanneer ik iemand zie die dezelfde interesses heeft als ik wil ik deze persoon "liken" zodat ik later een gesprek met deze persoon kan voeren.

Wanneer ik nog een date zoek wil ik mezelf registreren zodat ik binnen de app de juiste persoon kan vinden voor mij.

**Comment by rouws** [comment]
Beste Sjoerd,
Je hebt 2 job stories die er allebei goed uitzien. Wat mij betreft zijn beiden mogelijk, dus moet je gaan kiezen. Verder mis ik nog wel veel en kan ik daarom niet goed feedback geven. Ik zie geen ontwerp en geen static website, dus ik weet niet wat je van plan bent. 

Ik zie wel een wat onderzoek bij je benchmark dat is mooi. Je mag de mappen per vak weg gaan halen. Zet in je repository de code van je individuele opdracht. In je Wiki zet je al je onderzoek en ontwerpen.
