### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by SharonV33** [cmda-bt/pt-course-19-20#87]
# Job Story + stagic site

## Name
Sharon Veldman

## Class
tech2

## GitHub username

https://github.com/SharonV33/tech

## Job story
When i match with someone new
I want to talk to them 
so i can get to know them

**Comment by rouws** [comment]
Beste Sharon,
Je hebt een hele goede job story. En ook je benchmark ziet er goed uit. Bij de schetsen is het verstandig als je in detail gaat duiken van jouw job story de pagina's en states ontwerpt. Let op dat je je wiki goed gaat bijwerken, want ik zie al technische keuzes zoals de template engine en andere node packages, dus daar heb je waarschijnlijk onderzoek naar gedaan. Dat onderzoek moet je in je wiki gaan opnemen.

Bij je code mag je In ieder geval mag je een .gitignore file opnemen zodat je node_modules niet op Github komen. Het lijkt me ook niet handig om je app.js in een subfolder te zetten. En ook alles in een map 'server' zetten is misschien niet handig. Ik zie dingen met het weerbericht staan, die kan ik niet goed plaatsen. Ik wordt wel benieuwd naar wat je daarmee wil.  Je bent al lekker bezig met handlebars en templates en routes! Daar wordt ik heel blij van.
