### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by josdeboer24** [cmda-bt/pt-course-19-20#88]
# Job Story + stagic site

## Name
Jos de Boer

## Class
Tech 2

## GitHub username
josdeboer24 | https://github.com/josdeboer24/Block-tech/blob/master/index.html

## Job story

Wanneer ik zoek naar iemand wil ik dezelfde humor hebben als mijn match, zodat we het op dat gebied goed met elkaar kunnen vinden.

**Comment by rouws** [comment]
Hi Jos,

leuke job story.  De link naar je repository werkt niet meer, mogelijk heb je die repo verwijderd? Ik zie wel een andere repo staan, met daarin een klein beetje code. Voor mij is het nu niet mogelijk om echt feedback te geven. Je mag even een inhaalspurt doen om alles op github te zetten, je onderzoek en ontwerpen in je wiki. De code van je opdracht op de repository.
