### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by kilroy763** [cmda-bt/pt-course-19-20#89]
# Job Story + stagic site

## Name
Max Mulder

## Class
Tech 3

## GitHub username
Kilroy763

## Job stories
Wanneer ik op de datingsite kom wil ik inloggen of registreren zodat ik matches kan vinden die bij mij passen.

 https://kilroy763.github.io/Project_Tech/

**Comment by michaeldzjap** [comment]
Login pagina ziet er opzich prima uit. Misschien wil je nog wel er voor zorgen dat je als gebruiker verplicht wordt om ook daadwerkelijk iets in te vullen? Verder zou ik kiezen voor 1 van de 2 dingen; dus of een inlog, of een registratie functionaliteit bouwen. Beide mag ook, maar als je daarnaast ook nog een wachtwoord vergeten feature wilt inbouwen wordt het misschien wel een beetje veel qua werk. Of je zou zelfs er voor kunnen kiezen om alleen een wachtwoord vergeten / password recover functionaliteit te bouwen. Het voordeel daarvan zou kunnen zijn dat je makkelijk samen zou kunnen werken met iemand die alleen een inlog feature bouwt en een goede wachtwoord vergeten functionaliteit is al een aardige technische uitdaging op zichzelf. Dan zou je wel je job story moeten aanpassen. Kijk maar, het is jouw keuze.
