### ISSUE TITLE
INGE • first feedbackmoment

### ISSUE THREAD

**Issue by IngeDW** [cmda-bt/pt-course-19-20#90]
# Job Story + stagic site

## Name
Inge de Waard

## Class
3

## GitHub username
IngeDW
https://github.com/IngeDW/project-tech

## Job story
Wanneer ik als vrijgezel op de datingsite ben en iemand zoek om mee te daten, wil ik een profiel aanmaken, zodat ik actief kan zijn op de website en iemand kan gaan zoeken.

**Comment by michaeldzjap** [comment]
Zoals al in de klas besproken; je site ziet er tot nu toe heel netjes en verzorgd uit. En zoals ook al besproken; het uploaden van een image zou mooier zijn om te kunnen doen door op het `<img>` element te kunnen klikken. Of misschien wel zelfs makkelijker en gebruiksvriendelijker; om je `<img>` element "drag and droppable" te maken (zie [hier](https://www.w3schools.com/html/html5_draganddrop.asp) bv, maar daar bestaan ongetwijfeld ook de nodige JavaScript packages voor.).
