### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by SamSlotemaker** [cmda-bt/pt-course-19-20#91]
# Job Story + static site

## Name
Sam Slotemaker

## Class
tech 2

## GitHub username
https://github.com/SamSlotemaker/blok_tech

## Job story
Wanneer ik op de bank zit, wil ik kunnen aangeven of ik andere gebruikers wel of niet leuk vind, zodat ik hiermee kan connecten.

**Comment by rouws** [comment]
Hi Sam,
Je hebt een prima job story waar je mee verder kunt gaan. Mogelijk moet je hem op gegeven moment nog wel aanscherpen. Verder is het onderzoek in je wiki nog te minimaal. Het onderzoek in je benchmark is te beperkt nog. Voor mij is het nu niet mogelijk om echt feedback te geven. Je mag even een inhaalspurt doen om alles op github te zetten, je onderzoek en ontwerpen in je wiki. De code van je opdracht op de repository.
Ik zie wel dat je express en routing aan het verkennen bent, dat is goed.
