### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by thijsla** [cmda-bt/pt-course-19-20#92]
# Job Story + stagic site

## Name
Thijs Landsmeer

## Class
Tech 3

## GitHub username
Link naar statische site:
https://github.com/thijsla/project-tech

## Job story
Job Story nog niet bestaand

**Comment by michaeldzjap** [comment]
Heb je inmiddels wel een job story kunnen bedenken die je interessant zou vinden om verder uit te werken? Zo niet, dan is nu wel het moment om dat te gaan bepalen. Als ik je statische site bekijk dan lijkt je voorkeur uit te gaan naar een login / registreer feature? Dit is opzich OK, maar hou er wel rekening mee dat er al aardig wat van je mede klasgenoten ook een inlog / registreer feature willen ontwikkelen en daar al wel iets meer werk van hebben gemaakt in vergelijking tot jou. Dit kan een probleem zijn wanneer jullie in groepsverband aan het project gaan werken, dus dat is wel goed om je bewust van te zijn.

**Comment by thijsla** [comment]
Beste Michael,

Ik heb besloten om de filter functie uit te gaan werken. Dit omdat er
inderdaad al veel anderen bezig waren met inloggen/registeren. Ik werk ook
samen met Susanne, die het inloggen/registeren uit gaat werken.

Groeten,

Thijs Landsmeer
