### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by Yzerrr** [cmda-bt/pt-course-19-20#93]
# Job Story + stagic site

## Name
Joey

## Class
tech-2

## GitHub username
https://github.com/Yzerrr/project-t

## Job story
Als ik opzoek ben naar een match wil ik niet gelijk de foto’s kunnen bekijken zodat ik niet gelijk uit ga op het uiterlijk.

**Comment by rouws** [comment]
Hi Joey,
in de les hadden we al gesproken over het aanpassen van je job story. 

Voor mij is het nu niet mogelijk om echt feedback te geven. Je mag even een inhaalspurt doen om alles op github te zetten, je onderzoek en ontwerpen in je wiki. De code van je opdracht op de repository.
Ik zie wel al wat onderzoek in je benchmark, maar dat is nog wel wat beperkt.
