### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by Ch3relle** [cmda-bt/pt-course-19-20#94]
# Job Story + stagic site

## Name
Cherelle Bloem

## Class
Tech 2

## GitHub username
https://github.com/Ch3relle/pt-dating-app-2

## Job story

Wanneer ik een vrije avond heb dan wil ik een profiel aan kunnen maken zodat ik kan beginnen met het zoeken van een match.

**Comment by rouws** [comment]
Hi cherelle,
Je job story is prima, daar kun je goed mee verder. Verder hebben we in de les gesproken over wat je nu kunt doen. Zoek me op als je er niet uitkomt.

Voor mij is het nu niet mogelijk om echt feedback te geven. Je mag even een inhaalspurt doen om alles op github te zetten, je onderzoek en ontwerpen in je wiki. De code van je opdracht op de repository.
