### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by Ouiaam** [cmda-bt/pt-course-19-20#95]
# Job Story + stagic site

## Name
Ouiaam Mouyl

## Class
Tech_2

## GitHub username
https://github.com/Ouiaam/Project-Tech_2_ouiaam-

## Job story
Wanneer ik een avond vrij heb, wil ik matches krijgen gebaseerd op karaktereigenschappen en gelijkenissen, zodat ik contact kan leggen met een potentiële date.

**Comment by rouws** [comment]
Hi Ouiaam,

We hebben elkaar al in de les gesproken en hopelijk kon je daardoor verder. Ik dacht wel dat jij en Cherelle verschillende job stories hadden, maar als ik het nu lees lijken ze wel veel op elkaar. Dat is niet verstandig trouwens, dus zorg dat je echt iets maakt dat verschillend is. 
Voor mij is het nu niet mogelijk om echt feedback te geven. Je mag even een inhaalspurt doen om alles op github te zetten, je onderzoek en ontwerpen in je wiki. De code van je opdracht op de repository.
