### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by pepijnkok** [cmda-bt/pt-course-19-20#96]
# Job Story + stagic site

## Name
Pepijn Kok

## Class
Tech 2

## GitHub username
https://github.com/pepijnkok/blok-tech/tree/master/website

## Job story
Wanneer ik op reis ga wil ik graag vergezeld worden door een reispartner die dezelfde culturele intresses als ik heb, zodat ik naar mijn gewenste bestemming op reis kan gaan en deze ervaring samen met iemand kan delen.

**Comment by rouws** [comment]
Beste Pepijn,
in de les hadden we al gesproken over je job story en dat deze nog wel erg breed is mogelijk, maar je ideeen die je vertelde lijken me prima. Verder zie ik dat je al veel CSS hebt geschreven. In je wiki staat al wat onderzoek en ontwerpen, maar dit is nu nog te beperkt en mag je nog detailleren. 
Voor mij is het nu niet mogelijk om echt feedback te geven. Je mag even een inhaalspurt doen om alles op github te zetten, je onderzoek en ontwerpen in je wiki. De code van je opdracht op de repository.
