### ISSUE TITLE
first feedbackmoment

### ISSUE THREAD

**Issue by Awana1** [cmda-bt/pt-course-19-20#97]
# Job Story + stagic site

## Name

Azam Awan

## Class

203

## GitHub username

Awana1
https://github.com/Awana1/dating-app-pt/wiki

## Job story

Wanneer ik op school ben, wil ik mensen vinden op de dating app die met mij passen op basis van mijn persoonlijke voorkeur zodat ik sneller een match kan vinden.

## Comment

Ik heb grotendeels mijn tijd geïnvesteerd in het begrijpen van EJS. Ik heb nu voor elkaar gekregen om al mijn bestanden in EJS te converteren.

**Comment by rouws** [comment]
Beste Azam,
je hebt een goede job story. Ook zie ik een hele uitgebreide style guide, dat is mooi om te zien. Je wiki is verder nog leeg, dus je moet hier nog je schermontwerpen of wireframes in opnemen en belangrijk is ook het technisch onderzoek. Het technisch onderzoek is groot onderdeel van de eerste beoordeling.

De code die is zie is nog behoorlijk beperkt, dus daar kan ik niet echt feedback op geven, behalve dat je je .gitignore file niet moet vergeten. Ik had het idee toen ik je vanmiddag even sprak dat je al veel verder was met een template engine in ieder geval, dus top!

**Comment by Awana1** [comment]
Beste mevrouw Rouwhorst,


Ik heb een ander repository op github gemaakt voor blok tech. Mijn wiki is nu ook bijgewerkt met wat er verwacht wordt voor BT. Wegens familie omstandigheden ben ik iets later met het opleveren van de opdrachten, hoop dat dit geen problemen zal zijn bij het eind beoordeling.

PS: Mijn wiki is nog niet helemaal up to date. Enkele stukken moeten nog bijgewerkt worden. Zo heb ik bijvoorbeeld nog de states die toegevoegd moeten worden onder wireflow en jobstory

Link naar correcte repository: https://github.com/Awana1/Blok-Tech


Met vriendelijke groet,

Azam Awan

Van: Sonja Rouwhorst <notifications@github.com>
Beantwoorden - Aan: cmda-bt/pt-course-19-20 <reply@reply.github.com>
Datum: maandag 2 maart 2020 om 16:51
Aan: cmda-bt/pt-course-19-20 <pt-course-19-20@noreply.github.com>
CC: Azam Awan <azam.awan@hva.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [cmda-bt/pt-course-19-20] first feedbackmoment (#97)


Beste Azam,
je hebt een goede job story. Ook zie ik een hele uitgebreide style guide, dat is mooi om te zien. Je wiki is verder nog leeg, dus je moet hier nog je schermontwerpen of wireframes in opnemen en belangrijk is ook het technisch onderzoek. Het technisch onderzoek is groot onderdeel van de eerste beoordeling.

De code die is zie is nog behoorlijk beperkt, dus daar kan ik niet echt feedback op geven, behalve dat je je .gitignore file niet moet vergeten. Ik had het idee toen ik je vanmiddag even sprak dat je al veel verder was met een template engine in ieder geval, dus top!
