### ISSUE TITLE
Job Story - Marvin Sernee

### ISSUE THREAD

**Issue by MarvinMichel** [cmda-bt/pt-course-19-20#98]
# Job Story + stagic site

## Name
Marvin Sernee

## Class
Tech-3

## GitHub username
Repo: https://github.com/MarvinMichel/projectTech/tree/master/week%202

## Job story
https://github.com/MarvinMichel/projectTech/wiki/Benchmark,-Style-Guide-&-Job-Story#job-story

**Comment by michaeldzjap** [comment]
Je job story is goed uitgewerkt. Het is duidelijk wat je feature kan betekenen voor de gebruiker. Het enige waar je waarschijnlijk wel even goed over moet nadenken; een "liking" feature en een notification feature die de relevante personen op de hoogte stelt dat er wederzijdse interesse is zijn eigenlijk twee verschillende dingen. Natuurlijk kan de tweede feature niet zonder de eerste (je kan pas een notification sturen als je weet dat er een match is), maar het zijn wel 2 afzonderlijke stappen. Het is prima om ze allebei uit te werken, maar het is misschien wel iets meer werk dan je van tevoren inschat. Misschien is er al iemand die zich puur focused op het bouwen van een liking feature. Daar zou jouw notification feature dan natuurlijk mooi op aansluiten.
